BOARD_TAG=atmega328
ARDUINO_PORT=/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A900cf1Q-if00-port0
ARDUINO_LIBS=SPI Adafruit_MCP23017 SFRGBLEDMatrix DS1307 U8glib U8glib/utility HIH4030 DS18S20 BMP085 Wire Wire/utility EEPROM OneWire
ARDUINO_DIR=/home/fornellas/local/arduino-1.0.1
ARDMK_DIR=/home/fornellas/src/Arduino-Makefile
AVR_TOOLS_DIR=/usr
include /home/fornellas/src/Arduino-Makefile/arduino-mk/Arduino.mk
