BOARD_TAG=mega2560
ARDUINO_PORT=/dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Mega_2560_74133353537351606122-if00
ARDUINO_LIBS=SPI SFRGBLEDMatrix DS1307 U8glib U8glib/utility HIH4030 DS18S20 BMP085 Wire Wire/utility EEPROM OneWire Ethernet Ethernet/utility EthernetInterrupt MemoryFree SD
ARDUINO_DIR=/home/fornellas/local/arduino-1.0.1
ARDMK_DIR=/home/fornellas/src/Arduino-Makefile
AVR_TOOLS_DIR=/usr
include /home/fornellas/src/Arduino-Makefile/arduino-mk/Arduino.mk
MONITOR_BAUDRATE=115200
